import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

const products: IProductInput[] = [
  {
    name: "Nike Mens Slim-fit Long-Sleeve T-Shirt",
    slug: toSlug("Nike Mens Slim-fit Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: "Nike",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      "Made with chemicals safer for human health and the environment",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],
    reviews: [],
  },
  {
    name: "Muscle Cmdr Men's Slim Fit Henley Shirt",
    slug: toSlug("Muscle Cmdr Men's Slim Fit Henley Shirt"),
    category: "T-Shirts",
    brand: "Muscle Cmdr",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description: "Slim Fit Design: Men's Muscle Slim Fit Button Henley Shirts",
    sizes: ["XL", "XXL"],
    colors: ["Green", "Yellow"],
    reviews: [],
  },
  {
    name: "Adidas Essential Long-Sleeve T-Shirt",
    slug: toSlug("Adidas Essential Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Adidas",
    images: ["/images/p22-1.jpg", "/images/p22-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 24.99,
    listPrice: 29.99,
    avgRating: 4.5,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 4 },
    ],
    numSales: 15,
    countInStock: 20,
    description:
      "Comfortable and stylish long-sleeve t-shirt for everyday wear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Navy"],
    reviews: [],
  },
  {
    name: "Puma Classic Long Sleeve Tee",
    slug: toSlug("Puma Classic Long Sleeve Tee"),
    category: "T-Shirts",
    brand: "Puma",
    images: ["/images/p41-1.jpg", "/images/p42-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 22.5,
    listPrice: 27.5,
    avgRating: 4.3,
    numReviews: 6,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 2 },
      { rating: 5, count: 2 },
    ],
    numSales: 12,
    countInStock: 18,
    description: "Classic design with premium comfort",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Blue", "Grey"],
    reviews: [],
  },

  {
    name: "Jerzees Long-Sleeve Heavyweight Blend T-Shirt",
    slug: toSlug("Jerzees Long-Sleeve Heavyweight Blend T-Shirt"),
    category: "T-Shirts",
    images: [
      "/images/p12-1.jpg",
      "/images/p12-2.jpg",
      "/images/p12-3.jpg",
      "/images/p12-4.jpg",
    ],
    tags: ["featured"],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: "Jerzees",
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description: "Made with sustainably sourced USA grown cotton",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Yellow", "Red", "Black"],
    reviews: [],
  },
  {
    name: "Gildan Ultra Cotton Long Sleeve T-Shirt",
    slug: toSlug("Gildan Ultra Cotton Long Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Gildan",
    images: ["/images/p23-1.jpg", "/images/p35-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 19.99,
    listPrice: 24.99,
    avgRating: 4.6,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 11 },
    ],
    numSales: 45,
    countInStock: 30,
    description: "Ultra cotton for maximum comfort and durability",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: ["Black", "White", "Navy", "Red"],
    reviews: [],
  },
  {
    name: "Hanes ComfortSoft Long-Sleeve T-Shirt",
    slug: toSlug("Hanes ComfortSoft Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Hanes",
    images: ["/images/p36-1.jpg", "/images/p36-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 18.5,
    listPrice: 22.5,
    avgRating: 4.4,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 7 },
      { rating: 5, count: 8 },
    ],
    numSales: 38,
    countInStock: 25,
    description: "ComfortSoft fabric for all-day comfort",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "White", "Blue"],
    reviews: [],
  },

  {
    name: "Jerzees Men's Long-Sleeve T-Shirt",
    slug: toSlug("Jerzees Men Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description: "Made with dri-power technology that wicks away moisture",
    sizes: ["XL", "XXL"],
    colors: ["Green", "White"],
    reviews: [],
  },
  {
    name: "Hanes Mens Long Sleeve Beefy Henley Shirt",
    slug: toSlug("Hanes Mens Long Sleeve Beefy Henley Shirt"),
    category: "T-Shirts",
    brand: "Hanes",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description: "Heavyweight cotton for durability",
    sizes: ["XL", "XXL"],
    colors: ["Grey", "White"],
    reviews: [],
  },
  {
    name: "Fruit of the Loom Long Sleeve T-Shirt",
    slug: toSlug("Fruit of the Loom Long Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Fruit of the Loom",
    images: ["/images/p33-1.jpg", "/images/p33-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 15.99,
    listPrice: 19.99,
    avgRating: 4.2,
    numReviews: 28,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 10 },
      { rating: 5, count: 12 },
    ],
    numSales: 89,
    countInStock: 42,
    description: "Affordable quality for everyday wear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Grey", "Red"],
    reviews: [],
  },
  {
    name: "Champion Long-Sleeve T-Shirt",
    slug: toSlug("Champion Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Champion",
    images: ["/images/p35-1.jpg", "/images/p35-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 27.99,
    listPrice: 34.99,
    avgRating: 4.7,
    numReviews: 31,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 20 },
    ],
    numSales: 112,
    countInStock: 35,
    description: "Premium quality with Champion logo",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Red", "Green"],
    reviews: [],
  },

  {
    name: "Decrum Mens Plain Long Sleeve T-Shirt",
    slug: toSlug("Decrum Mens Plain Long Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Decrum",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 26.95,
    listPrice: 46.03,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description: "Soft long sleeve t shirt men",
    sizes: ["XL", "XXL"],
    colors: ["Yellow", "White"],
    reviews: [],
  },
  {
    name: "Under Armour Tech 2.0 Long Sleeve",
    slug: toSlug("Under Armour Tech 2.0 Long Sleeve"),
    category: "T-Shirts",
    brand: "Under Armour",
    images: ["/images/p25-1.jpg", "/images/p25-2.jpg"],
    tags: ["todays-deal", "featured"],
    isPublished: true,
    price: 32.99,
    listPrice: 45.0,
    avgRating: 4.8,
    numReviews: 42,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 10 },
      { rating: 5, count: 30 },
    ],
    numSales: 134,
    countInStock: 28,
    description: "UA Tech fabric for superior comfort",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey", "Navy"],
    reviews: [],
  },
];

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's Deal",
      href: "/search?tag=todays-deal",
    },
    {
      name: "New Arrival",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Featured Products",
      href: "/search?tag=featured",
    },
    {
      name: "Best Sellers",
      href: "/search?tag=best-seller",
    },
    {
      name: "Browsing History",
      href: "/#browsing-history",
    },
    {
      name: "Customer Service",
      href: "/page/customer-service",
    },
    {
      name: "About Us",
      href: "/page/about-us",
    },
    {
      name: "Help",
      href: "/page/help",
    },
  ],

  carousels: [
    {
      title: "Most Popular Shoes For Sale",
      buttonCaption: "Show Now",
      image: "/images/banner3.jpg",
      url: "/search?category=Shoes",
      isPublished: true,
    },
    {
      title: "Best Selling in T-shirts",
      buttonCaption: "Shop Now",
      image: "/images/banner1.jpg",
      url: "/search?category=T-shirts",
      isPublished: true,
    },
    {
      title: "Best Deals on Wrist Watches",
      buttonCaption: "See More",
      image: "/images/banner2.jpg",
      url: "/search?category=Wrist Watches",
      isPublished: true,
    },
  ],
};

export default data;
